# Generated by Django 5.2.3 on 2025-07-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Введите id сессии", max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                default="transfer",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
