# Generated by Django 5.2.3 on 2025-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Введите цену",
                max_digits=10,
                null=True,
                verbose_name="Цена за покупку",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Введите цену",
                max_digits=10,
                null=True,
                verbose_name="Цена за покупку",
            ),
        ),
    ]
